SERVICE := go-hotreload

dev:
  GO_MOD=go.mod docker-compose up

dev-build:
  GO_MOD=go.mod docker-compose up --build

dev-local:
  GO_MOD=go.local.mod docker-compose up

dev-local-build:
  GO_MOD=go.local.mod docker-compose up --build
